Apache Beam doesn't support PEP 585
> TypeError: PEP 585 generic type hints like dict[str, typing.Any] are not yet supported,
> use typing module containers instead. See equivalents listed at https://docs.python.org/3/library/typing.html